server:
  port: 8088
  servlet:
    context-path: /example

spring:
  profiles:
    active: dev

  # 应用配置
  application:
    name: dynamic-threadpool-example

  # 动态线程池配置
  dynamic:
    thread-pool:
      server-addr: http://192.168.40.73:6691
      namespace: channel-dev
      item-id: channel
      username: admin
      password: 123456
      enable: true
